# Generated by Django 5.0.6 on 2024-06-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrello',
            options={'verbose_name_plural': 'Carrelli'},
        ),
        migrations.AlterModelOptions(
            name='carrelloprodotto',
            options={'verbose_name_plural': 'Prodotti Carrello'},
        ),
        migrations.AlterModelOptions(
            name='prenotazione',
            options={'verbose_name_plural': 'Prenotazioni'},
        ),
        migrations.AlterModelOptions(
            name='prenotazioneprodotto',
            options={'verbose_name_plural': 'Prodotti Prenotazione'},
        ),
    ]
